name: CI Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test automatici
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v7

      - name: Configurazione Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Installazione dipendenze
        run: pip install -r requirements.txt

      - name: Esecuzione test
        run: pytest -v